### ISSUE TITLE
Illuminate\Cache\RedisStore does not implement Illuminate\Contracts\Cache\Repository

### ISSUE THREAD

**Issue by northeaster** [FriendsOfFlarum/terms#21]
may be related to recache ext https://extiverse.com/extension/reflar/recache

```
# php flarum info
Flarum core 0.1.0-beta.13
PHP version: 7.4.5
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imap, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+----------------------------------+-------------------+--------+
| Flarum Extensions                |                   |        |
+----------------------------------+-------------------+--------+
| ID                               | Version           | Commit |
+----------------------------------+-------------------+--------+
| flarum-approval                  | v0.1.0-beta.13    |        |
| flarum-flags                     | v0.1.0-beta.13    |        |
| flarum-likes                     | v0.1.0-beta.13    |        |
| flarum-lock                      | v0.1.0-beta.13    |        |
| flarum-markdown                  | v0.1.0-beta.13    |        |
| flarum-mentions                  | v0.1.0-beta.13    |        |
| flarum-sticky                    | v0.1.0-beta.13    |        |
| flarum-subscriptions             | v0.1.0-beta.13    |        |
| flarum-suspend                   | v0.1.0-beta.13    |        |
| flarum-tags                      | v0.1.0-beta.13    |        |
| flarum-emoji                     | v0.1.0-beta.13    |        |
| flarum-lang-english              | v0.1.0-beta.13    |        |
| fof-transliterator               | 0.2.0             |        |
| fof-pages                        | 0.4.0             |        |
| fof-user-directory               | 0.3.4             |        |
| fof-merge-discussions            | 0.3.3             |        |
| flagrow-ads                      | 0.2.4             |        |
| fof-best-answer                  | 0.1.7             |        |
| fof-drafts                       | 0.1.5             |        |
| fof-links                        | 0.3.0             |        |
| fof-user-bio                     | 0.1.3             |        |
| v17development-seo               | 1.2               |        |
| fof-follow-tags                  | 0.3.4             |        |
| fof-socialprofile                | 0.1.2             |        |
| kilowhat-mailing                 | 0.2.3             |        |
| fof-subscribed                   | 0.2.3             |        |
| fof-formatting                   | 0.1.4             |        |
| fof-reactions                    | 0.3.1             |        |
| flarum-auth-github               | v0.1.0-beta.13    |        |
| fof-recaptcha                    | 0.1.2             |        |
| saleksin-auth-google             | v0.1.0-beta.8.0.3 |        |
| flarum-auth-facebook             | v0.1.0-beta.13    |        |
| fof-auth-discord                 | 0.1.3             |        |
| flarum-auth-twitter              | v0.1.0-beta.13    |        |
| fof-polls                        | 0.1.2             |        |
| fof-byobu                        | 0.5.0             |        |
| jordanjay29-summaries            | 0.3.1             |        |
| flagrow-analytics                | 0.8.0             |        |
| fof-geoip                        | 0.1.7             |        |
| flarum-bbcode                    | v0.1.0-beta.12    |        |
| fof-upload                       | 0.9.1             |        |
| flarum-pusher                    | v0.1.0-beta.13    |        |
| isaced-email-verification-switch | 0.1.3             |        |
| fof-realtimedate                 | 0.1.2             |        |
| tolgaaaltas-turkish              | 0.13.2            |        |
| tolgaaaltas-lang-turkish         | 0.13.0            |        |
| fof-profile-image-crop           | 0.1.1             |        |
| flarum-statistics                | v0.1.0-beta.13    |        |
| clarkwinkelmann-circle-groups    | 0.2.1             |        |
| flagrow-sitemap                  | 0.2.0             |        |
| michaelbelgium-discussion-views  | v3.2.0            |        |
| simonxeko-follow-users           | 0.3.5             |        |
| therealsujitk-gifs               | v1.4.8            |        |
| zerosonesfun-hashtags            | 2.0.1             |        |
| askvortsov-moderator-warnings    | v0.1.5            |        |
| fof-spamblock                    | 0.2.2             |        |
| fof-share-social                 | 0.1.2             |        |
| nomiscz-auth-steam               | v0.1.7            |        |
| the-turk-password-strength       | 0.1.3             |        |
| michaelbelgium-profile-views     | v2.1.6            |        |
| amaurycarrade-syndication        | v0.3.1            |        |
| therealsujitk-show-password      | v1.0.3            |        |
| fof-nightmode                    | 0.4.0             |        |
| the-turk-diff                    | 1.0.6             |        |
| reflar-recache                   | 2.0.3             |        |
+----------------------------------+-------------------+--------+
Base URL: https://forum.sourceturk.net
Installation path: /var/www/sourceturk/forum
Debug mode: off
```

```
[2020-05-14 06:53:33] production.ERROR: TypeError: Argument 3 passed to FoF\Terms\Repositories\PolicyRepository::__construct() must implement interface Illuminate\Contracts\Cache\Repository, instance of Illuminate\Cache\RedisStore given in /var/www/sourceturk/forum/vendor/fof/terms/src/Repositories/PolicyRepository.php:24
Stack trace:
#0 [internal function]: FoF\Terms\Repositories\PolicyRepository->__construct()
#1 /var/www/sourceturk/forum/vendor/illuminate/container/Container.php(812): ReflectionClass->newInstanceArgs()
#2 /var/www/sourceturk/forum/vendor/illuminate/container/Container.php(658): Illuminate\Container\Container->build()
#3 /var/www/sourceturk/forum/vendor/illuminate/container/Container.php(609): Illuminate\Container\Container->resolve()
#4 /var/www/sourceturk/forum/vendor/flarum/core/src/Foundation/Application.php(521): Illuminate\Container\Container->make()
#5 /var/www/sourceturk/forum/vendor/flarum/core/src/helpers.php(26): Flarum\Foundation\Application->make()
#6 /var/www/sourceturk/forum/vendor/fof/terms/src/Extenders/ForumPoliciesRelationship.php(30): app()
#7 /var/www/sourceturk/forum/vendor/illuminate/events/Dispatcher.php(360): FoF\Terms\Extenders\ForumPoliciesRelationship->loadRelationship()
#8 /var/www/sourceturk/forum/vendor/illuminate/events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#9 /var/www/sourceturk/forum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(99): Illuminate\Events\Dispatcher->dispatch()
#10 /var/www/sourceturk/forum/vendor/flarum/core/src/Api/Client.php(72): Flarum\Api\Controller\AbstractSerializeController->handle()
#11 /var/www/sourceturk/forum/vendor/flarum/core/src/Frontend/Frontend.php(72): Flarum\Api\Client->send()
#12 /var/www/sourceturk/forum/vendor/flarum/core/src/Frontend/Frontend.php(51): Flarum\Frontend\Frontend->getForumDocument()
#13 /var/www/sourceturk/forum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#14 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle()
#15 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#16 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#17 /var/www/sourceturk/forum/vendor/flarum/core/src/Admin/Middleware/RequireAdministrateAbility.php(26): Laminas\Stratigility\Next->handle()
#18 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Admin\Middleware\RequireAdministrateAbility->process()
#19 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#20 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#21 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#22 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#23 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#24 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#25 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#26 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#27 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#28 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#29 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#30 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#31 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#32 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#33 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#34 /var/www/sourceturk/forum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#35 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#36 /var/www/sourceturk/forum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#37 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#38 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#39 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#40 /var/www/sourceturk/forum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#41 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#42 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#43 /var/www/sourceturk/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#44 /var/www/sourceturk/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#45 /var/www/sourceturk/forum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#46 /var/www/sourceturk/forum/public/index.php(22): Flarum\Http\Server->listen()
#47 {main}  
```

**Comment by clarkwinkelmann** [comment]
@KyrneDev could you share your thoughts on this ? Could there be a faulty binding in Recache ?

As I understand, both reflar/recache and bokt/redis provide a Redis cache driver ?

I couldn't find any issue with https://github.com/Bokt/flarum-redis/blob/master/src/Provides/Cache.php, but it seems it's not installed here anyway, so it must be related to Recache.

**Comment by northeaster** [comment]
@clarkwinkelmann I stopped using the ReCache plugin. I found a lot of errors and @KyrneDev fixed it. I remember that this error was corrected with version 2.0.6.

**Comment by datitisev** [comment]
This is a recache or redis ext issue, so in closing this.

**Comment by KyrneDev** [comment]
It was related to recache but I got it all patched up.
